# -------------------------------------------------------
# 민감 정보 Secret
# 실제 배포 시 값을 Base64로 인코딩하거나 AWS Secrets Manager / External Secrets Operator 사용 권장
# echo -n "1234" | base64  →  MTIzNA==
# -------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: autonix-secrets
  namespace: autonix
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "1234"   # TODO: 실제 배포 전 변경
  DB_USERNAME: "root"
  DB_PASSWORD: "1234"           # TODO: 실제 배포 전 변경
