apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: autonix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service
          image: 088153173875.dkr.ecr.ap-northeast-2.amazonaws.com/autonix/shipping-service:latest
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: autonix-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: autonix-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: SPRING_KAFKA_CONSUMER_GROUP_ID
              value: "shipping-group"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: autonix-config
                  key: EUREKA_URL
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://autonix.cfsm44ue6k13.ap-northeast-2.rds.amazonaws.com:3306/shipping_db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true"
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: autonix-secrets
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: autonix-secrets
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shipping-service-svc
  namespace: autonix
spec:
  selector:
    app: shipping-service
  ports:
    - port: 8085
      targetPort: 8085
